name: example
description: A new Flutter project.
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  sign_in_button_plus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true
