name: sign_in_button_plus
description: A Flutter plugin for generating sign-in buttons for different social media accounts.
homepage: https://github.com/anmolthedeveloper/sign_in_button_plus
version: 1.0.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logos/google_light.png
    - assets/logos/google_dark.png
    - assets/logos/facebook_new.png
    - assets/logos/2.0x/
    - assets/logos/3.0x/
